version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=payment
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: 'redis:latest'
    ports:
      - 6380:6379
