version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 33006:3307
    environment:
      - MYSQL_DATABASE=DYMall
      - MYSQL_USER=DYMall
      - MYSQL_PASSWORD=DYMall
      - MYSQL_ROOT_PASSWORD="DYMall"
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
  consul:
    image: 'consul:latest'
    ports:
      - 8500:8500
    command:
      - 'agent -dev -client=0.0.0.0'

